import type { CSSProperties } from "react";

// Light-mode theme tuned to feel close to coldarkDark without importing a Prism light preset.
export const coldarkLightLike: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: "#1f2937",
    background: "none",
    fontFamily:
      "var(--font-geist-mono), ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
  'pre[class*="language-"]': {
    color: "#1f2937",
    background: "#f8fafc",
    margin: 0,
    padding: "1rem",
    overflow: "auto",
  },
  comment: { color: "#6b7280", fontStyle: "italic" },
  prolog: { color: "#6b7280" },
  doctype: { color: "#6b7280" },
  cdata: { color: "#6b7280" },
  punctuation: { color: "#374151" },
  property: { color: "#7c3aed" },
  tag: { color: "#be185d" },
  boolean: { color: "#0f766e" },
  number: { color: "#0f766e" },
  constant: { color: "#0f766e" },
  symbol: { color: "#0f766e" },
  deleted: { color: "#dc2626" },
  selector: { color: "#2563eb" },
  "attr-name": { color: "#2563eb" },
  string: { color: "#0f766e" },
  char: { color: "#0f766e" },
  builtin: { color: "#2563eb" },
  inserted: { color: "#16a34a" },
  operator: { color: "#374151" },
  entity: { color: "#2563eb", cursor: "help" },
  url: { color: "#2563eb" },
  variable: { color: "#b45309" },
  atrule: { color: "#7c3aed" },
  keyword: { color: "#7c3aed", fontWeight: 600 },
  function: { color: "#1d4ed8" },
  "class-name": { color: "#1d4ed8" },
  regex: { color: "#be185d" },
  important: { color: "#be185d", fontWeight: 700 },
};

// Dark-mode theme based on coldarkDark — local copy for easy customisation.
export const coldarkDarkLike: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: "#e3eaf2",
    background: "none",
    fontFamily:
      "var(--font-geist-mono), ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
  'pre[class*="language-"]': {
    color: "#e3eaf2",
    background: "#0a050f",
    margin: 0,
    padding: "1rem",
    overflow: "auto",
  },
  comment: { color: "#8da1b9", fontStyle: "italic" },
  prolog: { color: "#8da1b9" },
  doctype: { color: "#8da1b9" },
  cdata: { color: "#8da1b9" },
  punctuation: { color: "#e3eaf2" },
  "delimiter.important": { color: "#66cccc", fontWeight: "inherit" },
  "selector.parent": { color: "#66cccc" },
  tag: { color: "#66cccc" },
  "tag.punctuation": { color: "#66cccc" },
  "attr-name": { color: "#e6d37a" },
  boolean: { color: "#e6d37a" },
  "boolean.important": { color: "#e6d37a" },
  number: { color: "#e6d37a" },
  constant: { color: "#e6d37a" },
  "selector.attribute": { color: "#e6d37a" },
  "class-name": { color: "#6cb8e6" },
  key: { color: "#6cb8e6" },
  parameter: { color: "#6cb8e6" },
  property: { color: "#6cb8e6" },
  "property-access": { color: "#6cb8e6" },
  variable: { color: "#6cb8e6" },
  "attr-value": { color: "#91d076" },
  inserted: { color: "#91d076" },
  color: { color: "#91d076" },
  "selector.value": { color: "#91d076" },
  string: { color: "#91d076" },
  "string.url-link": { color: "#91d076" },
  builtin: { color: "#f4adf4" },
  "keyword-array": { color: "#f4adf4" },
  package: { color: "#f4adf4" },
  regex: { color: "#f4adf4" },
  function: { color: "#c699e3" },
  "selector.class": { color: "#c699e3" },
  "selector.id": { color: "#c699e3" },
  "atrule.rule": { color: "#e9ae7e" },
  combinator: { color: "#e9ae7e" },
  keyword: { color: "#e9ae7e" },
  operator: { color: "#e9ae7e" },
  "pseudo-class": { color: "#e9ae7e" },
  "pseudo-element": { color: "#e9ae7e" },
  selector: { color: "#e9ae7e" },
  unit: { color: "#e9ae7e" },
  deleted: { color: "#cd6660" },
  important: { color: "#cd6660", fontWeight: "bold" },
  "keyword-this": { color: "#6cb8e6", fontWeight: "bold" },
  this: { color: "#6cb8e6", fontWeight: "bold" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
  entity: { cursor: "help" },
};
