#!/usr/bin/env node

import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { componentDocSchema } from "../src/lib/component-doc-schema.ts";
import { getDemoNames } from "./lib/docs.mjs";

const root = path.resolve(import.meta.dirname, "..");
const contentDir = path.join(root, "content", "components");
const outputPath = path.join(root, "src", "generated", "component-index.ts");
const demoMapPath = path.join(root, "src", "generated", "demo-map.ts");
const registry = JSON.parse(
  fs.readFileSync(path.join(root, "registry.json"), "utf8"),
);
// Demo names come from the per-slug demo convention
// (src/demos/<slug>.tsx) — no source parsing involved.
const demoNames = getDemoNames();

function getDocFiles(directory = contentDir) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return getDocFiles(entryPath);
    return entry.name.endsWith(".mdx") ? [entryPath] : [];
  });
}

const docs = getDocFiles()
  .sort()
  .map((filePath) => {
    const slug = path.basename(filePath, ".mdx");
    const { data } = matter(fs.readFileSync(filePath, "utf8"));
    return { slug, ...componentDocSchema.parse(data) };
  });

for (const item of registry.items) {
  if (!docs.some((doc) => doc.slug === item.name)) {
    throw new Error(
      `Missing MDX documentation for registry component "${item.name}".`,
    );
  }
}

// Inverse direction: every MDX doc must belong to a registered component,
// otherwise it appears in the sidebar but cannot be installed.
const registered = new Set(registry.items.map((item) => item.name));
for (const doc of docs) {
  if (!registered.has(doc.slug)) {
    throw new Error(
      `Orphan MDX doc "${doc.slug}" has no registry.json entry. Add the component to registry.json or remove the doc.`,
    );
  }
}

const output =
  `// Generated by scripts/build-docs.mjs. Do not edit manually.\n` +
  `import type { ComponentCategory } from "@/lib/component-categories";\n\n` +
  `export interface ComponentIndexItem {\n` +
  `  slug: string;\n  title: string;\n  description: string;\n  category: ComponentCategory;\n}\n\n` +
  `export const componentIndex: ComponentIndexItem[] = ${JSON.stringify(
    docs.map(({ slug, title, description, category }) => ({
      slug,
      title,
      description,
      category,
    })),
    null,
    2,
  )} as ComponentIndexItem[];\n`;

const demoEntries = demoNames
  .map((name) => `  "${name}": dynamic(() => import("@/demos/${name}")),`)
  .join("\n");

const demoMapOutput =
  `// Generated by scripts/build-docs.mjs. Do not edit manually.\n` +
  `import dynamic from "next/dynamic";\n\n` +
  `export const demos = {\n${demoEntries}\n} as const;\n\n` +
  `export type DemoName = keyof typeof demos;\n`;

const outputs = [
  { path: outputPath, content: output, label: "component index" },
  { path: demoMapPath, content: demoMapOutput, label: "demo map" },
];

if (process.argv.includes("--check")) {
  for (const { path: outPath, content, label } of outputs) {
    if (
      !fs.existsSync(outPath) ||
      fs.readFileSync(outPath, "utf8") !== content
    ) {
      throw new Error(
        `${label} is stale. Run bun docs:build and commit the result.`,
      );
    }
  }
  console.log(
    `✓ Validated ${docs.length} MDX documents, ${demoNames.length} demos`,
  );
} else {
  for (const { path: outPath, content } of outputs) {
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, content);
  }
  console.log(`✓ Generated component index with ${docs.length} documents`);
  console.log(`✓ Generated demo map with ${demoNames.length} demos`);
}
