#!/usr/bin/env node

import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { createComponentDocSchema } from "./component-doc-schema.mjs";

const root = path.resolve(import.meta.dirname, "..");
const contentDir = path.join(root, "content", "components");
const outputPath = path.join(root, "src", "generated", "component-index.ts");
const registry = JSON.parse(fs.readFileSync(path.join(root, "registry.json"), "utf8"));
const demoSource = fs.readFileSync(
  path.join(root, "src", "components", "docs", "DemoRenderer.tsx"),
  "utf8",
);
const demoNames = new Set(
  [...demoSource.matchAll(/^\s*"([^"]+)":\s*dynamic\(/gm)].map((match) => match[1]),
);
const componentDocSchema = createComponentDocSchema(demoNames);

function getDocFiles(directory = contentDir) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return getDocFiles(entryPath);
    return entry.name.endsWith(".mdx") ? [entryPath] : [];
  });
}

const docs = getDocFiles()
  .sort()
  .map((filePath) => {
    const slug = path.basename(filePath, ".mdx");
    const { data } = matter(fs.readFileSync(filePath, "utf8"));
    return { slug, ...componentDocSchema.parse(data) };
  });

for (const item of registry.items) {
  if (!docs.some((doc) => doc.slug === item.name)) {
    throw new Error(`Missing MDX documentation for registry component "${item.name}".`);
  }
}

const output = `// Generated by scripts/build-docs.mjs. Do not edit manually.\n` +
  `import type { ComponentCategory } from "@/lib/component-categories";\n\n` +
  `export interface ComponentIndexItem {\n` +
  `  slug: string;\n  title: string;\n  description: string;\n  category: ComponentCategory;\n}\n\n` +
  `export const componentIndex: ComponentIndexItem[] = ${JSON.stringify(
    docs.map(({ slug, title, description, category }) => ({ slug, title, description, category })),
    null,
    2,
  )} as ComponentIndexItem[];\n`;

if (process.argv.includes("--check")) {
  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== output) {
    throw new Error("Component index is stale. Run bun docs:build and commit the result.");
  }
  console.log(`✓ Validated ${docs.length} MDX documents`);
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output);
  console.log(`✓ Generated component index with ${docs.length} documents`);
}
