#!/usr/bin/env node

import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { createComponentDocSchema } from "../src/lib/component-doc-schema.ts";

const root = path.resolve(import.meta.dirname, "..");
const contentDir = path.join(root, "content", "components");
const outputPath = path.join(root, "src", "generated", "component-index.ts");
const registry = JSON.parse(
  fs.readFileSync(path.join(root, "registry.json"), "utf8"),
);
const demoSource = fs.readFileSync(
  path.join(root, "src", "components", "docs", "DemoRenderer.tsx"),
  "utf8",
);
const demoNames = new Set(
  [...demoSource.matchAll(/^\s*"([^"]+)":\s*dynamic\(/gm)].map(
    (match) => match[1],
  ),
);
const componentDocSchema = createComponentDocSchema(demoNames);

function getDocFiles(directory = contentDir) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return getDocFiles(entryPath);
    return entry.name.endsWith(".mdx") ? [entryPath] : [];
  });
}

const docs = getDocFiles()
  .sort()
  .map((filePath) => {
    const slug = path.basename(filePath, ".mdx");
    const { data } = matter(fs.readFileSync(filePath, "utf8"));
    return { slug, ...componentDocSchema.parse(data) };
  });

for (const item of registry.items) {
  if (!docs.some((doc) => doc.slug === item.name)) {
    throw new Error(
      `Missing MDX documentation for registry component "${item.name}".`,
    );
  }
}

// Inverse direction: every MDX doc must belong to a registered component,
// otherwise it appears in the sidebar but cannot be installed.
const registered = new Set(registry.items.map((item) => item.name));
for (const doc of docs) {
  if (!registered.has(doc.slug)) {
    throw new Error(
      `Orphan MDX doc "${doc.slug}" has no registry.json entry. Add the component to registry.json or remove the doc.`,
    );
  }
}

const output =
  `// Generated by scripts/build-docs.mjs. Do not edit manually.\n` +
  `import type { ComponentCategory } from "@/lib/component-categories";\n\n` +
  `export interface ComponentIndexItem {\n` +
  `  slug: string;\n  title: string;\n  description: string;\n  category: ComponentCategory;\n}\n\n` +
  `export const componentIndex: ComponentIndexItem[] = ${JSON.stringify(
    docs.map(({ slug, title, description, category }) => ({
      slug,
      title,
      description,
      category,
    })),
    null,
    2,
  )} as ComponentIndexItem[];\n`;

// ─── MCP data (self-contained catalog for /api/mcp — zero runtime fs) ──────
const registryByName = new Map(registry.items.map((item) => [item.name, item]));
const REGISTRY_BASE = registry.homepage;

const mcpComponents = docs.map((doc) => {
  const item = registryByName.get(doc.slug);
  const sourcePath = item?.files?.[0]?.path;
  const sourceCode = sourcePath
    ? fs
        .readFileSync(path.join(root, sourcePath), "utf8")
        .replace(/\r\n?/g, "\n")
    : "";
  const installCommand = `${REGISTRY_BASE}/r/${doc.slug}.json`;
  return {
    name: doc.slug,
    title: doc.title,
    description: doc.description,
    category: doc.category,
    dependencies: item?.dependencies ?? [],
    registryDependencies: item?.registryDependencies ?? [],
    props: doc.props,
    usage: doc.usage,
    sourceCode,
    installCommand,
  };
});

const mcpOutput =
  `// Generated by scripts/build-docs.mjs. Do not edit manually.\n\n` +
  `export interface McpComponentProp {\n` +
  `  name: string;\n  type: string;\n  default?: string;\n  description?: string;\n}\n\n` +
  `export interface McpComponent {\n` +
  `  name: string;\n  title: string;\n  description: string;\n  category: string;\n` +
  `  dependencies: string[];\n  registryDependencies: string[];\n` +
  `  props: McpComponentProp[];\n  usage: string;\n  sourceCode: string;\n` +
  `  installCommand: string;\n}\n\n` +
  `export const mcpComponents: McpComponent[] = ${JSON.stringify(
    mcpComponents,
    null,
    2,
  )};\n`;

const mcpOutputPath = path.join(root, "src", "generated", "mcp-data.ts");

if (process.argv.includes("--check")) {
  if (
    !fs.existsSync(outputPath) ||
    fs.readFileSync(outputPath, "utf8") !== output
  ) {
    throw new Error(
      "Component index is stale. Run bun docs:build and commit the result.",
    );
  }
  if (
    !fs.existsSync(mcpOutputPath) ||
    fs.readFileSync(mcpOutputPath, "utf8") !== mcpOutput
  ) {
    throw new Error(
      "MCP data is stale. Run bun docs:build and commit the result.",
    );
  }
  console.log(`✓ Validated ${docs.length} MDX documents`);
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output);
  console.log(`✓ Generated component index with ${docs.length} documents`);
  fs.writeFileSync(mcpOutputPath, mcpOutput);
  console.log(`✓ Generated MCP data with ${mcpComponents.length} components`);
}
